spring:
  application:
    name: palantir-telegram-adapter
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
    password: '@db.password@'
    type: com.zaxxer.hikari.HikariDataSource
    url: '@db.url@'
    username: '@db.user@'
    flyway:
      enabled: true
      password: '@db.password@'
      url: '@db.url@'
      user: '@db.user@'
    jpa:
      database: postgresql
      properties:
        hibernate:
          id:
            new_generator_mappings: false
  cloud:
    stream:
      kafka:
#        binder:
#          brokers: 0.0.0.0:9092
        bindings:
          default:
            consumer:
              start-offers: latest
      bindings:
        userSearchRequest:
          destination: userSearchRequest
        userSearchResponse:
          destination: userSearchResponse
  kafka:
    bootstrap-servers: ${kafka_bootstrap_servers:localhost:9092}
    properties:
      sasl:
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username=${kafka_username:'admin'} password=${kafka_password:'admin-secret'};
        mechanism: PLAIN
      security:
        protocol: SASL_PLAINTEXT
server:
  port: 8081
bot:
  name: ${BOT_NAME}
  token: ${BOT_TOKEN}